url: "https://groove2groove.telecom-paris.fr"
baseurl: "/"
title: "Groove2Groove"

defaults:
  - scope:
      path: ""
    values:
      entry: common

sass:
  sourcemap: development

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - yarn.lock
  - yarn-error.log
  - webpack.*.js
  - tsconfig.json
  - dist
  - deploy.sh
  # dot files are excluded by default

include:
  - .htaccess

keep_files:
  - .git
  - .svn
  - data
